name: laplace_kernel_in_cl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2026.3.19
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.5
  - pthread-stubs=0.3
  - python=3.9.18
  - readline=8.3
  - sqlite=3.51.2
  - tk=8.6.15
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.2
  - zlib=1.3.1
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.9.0
      - aiosignal==1.2.0
      - astroid==3.3.11
      - async-timeout==4.0.3
      - attrs==23.1.0
      - blinker==1.6.2
      - brotli==1.0.9
      - cachetools==4.2.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==2.0.4
      - click==8.1.7
      - continuum==1.2.7
      - contourpy==1.2.0
      - cryptography==41.0.3
      - cycler==0.12.1
      - datasets==4.1.1
      - dill==0.4.0
      - dodgy==0.2.1
      - easydict==1.13
      - exceptiongroup==1.3.0
      - filelock==3.15.4
      - flake8==7.3.0
      - flake8-polyfill==1.0.2
      - fonttools==4.47.2
      - frozenlist==1.4.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - google-auth==2.22.0
      - google-auth-oauthlib==0.5.2
      - grpcio==1.48.2
      - h5py==3.14.0
      - huggingface-hub==0.24.0
      - idna==3.4
      - imagehash==4.3.2
      - imageio==2.37.0
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - iniconfig==2.1.0
      - intel-cmplr-lib-ur==2025.3.3
      - intel-openmp==2025.3.3
      - isort==6.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - littleutils==0.2.4
      - markdown==3.4.1
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mccabe==0.7.0
      - mkl==2025.3.1
      - mkl-fft==1.3.8
      - mkl-random==1.2.4
      - mkl-service==2.4.0
      - mock==5.2.0
      - multidict==6.0.4
      - multiprocess==0.70.16
      - mypy==1.18.1
      - mypy-extensions==1.1.0
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - ogb==1.3.6
      - onemkl-license==2025.3.1
      - open-clip-torch==2.22.0
      - opencv-python==4.11.0.86
      - outdated==0.2.2
      - packaging==23.2
      - pandas==2.3.2
      - pathspec==0.12.1
      - pep8-naming==0.10.0
      - pillow==10.0.1
      - pip==23.3.1
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - prospector==1.17.3
      - protobuf==3.20.3
      - pyarrow==21.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycodestyle==2.14.0
      - pycparser==2.21
      - pydocstyle==6.3.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyjwt==2.4.0
      - pylint==3.3.8
      - pylint-celery==0.3
      - pylint-django==2.6.1
      - pylint-plugin-utils==0.9.0
      - pyopenssl==23.2.0
      - pyparsing==3.1.1
      - pysocks==1.7.1
      - pytest==8.4.2
      - pytest-mock==3.15.1
      - python-dateutil==2.8.2
      - pytz==2025.2
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - regex==2024.11.6
      - requests==2.32.5
      - requests-oauthlib==1.3.0
      - requirements-detector==1.4.0
      - rsa==4.7.2
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - semver==3.0.4
      - sentencepiece==0.2.0
      - setoptconf-tmp==0.3.1
      - setuptools==68.0.0
      - six==1.16.0
      - snowballstemmer==3.0.1
      - tbb==2022.3.1
      - tcmlib==1.4.1
      - tensorboard==2.12.1
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==0.9.7
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.67.1
      - typing-extensions==4.7.1
      - tzdata==2025.2
      - umf==1.0.3
      - urllib3==1.26.18
      - wcwidth==0.2.13
      - werkzeug==2.3.8
      - wheel==0.41.2
      - wilds==2.0.0
      - xxhash==3.5.0
      - yarl==1.9.3
      - zipp==3.17.0