import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# ============================================================
# 1. Configuration & Data Loading
# ============================================================
file_path = 'log_likelihood_values_vit_4_classes.txt'

try:
    df = pd.read_csv(file_path, sep=r'\s+')
except FileNotFoundError:
    print(f"Error: File '{file_path}' not found. Make sure it was generated by the training script.")
    exit()

plt.rcParams.update({
    "text.usetex": False,
    "font.family": "serif",
    "font.size": 9,
    "axes.labelsize": 10,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 8
})

layers = [f'block{i}' for i in range(12)]
DIM = 768

fig, axes = plt.subplots(3, 4, figsize=(16, 7.5), sharex=True)
axes = axes.flatten()

for i, l in enumerate(layers):
    ax = axes[i]
    epochs = df['Epoch']
    
    base_ll_val = df[f'{l}_Baseline'].mean()
    lcm_ll = df[f'{l}_LCM']
    
    ax.axhline(base_ll_val, linestyle='--', linewidth=1.4, color='#555555', zorder=3, label='Diag. Cov.')
    
    ax.plot(epochs, lcm_ll, linestyle='-', linewidth=2.0, color='#e67e22', zorder=4, label='Full Cov.')
    
    title_text = f'Block {i} ($D = {DIM}$)'
    ax.text(0.5, 0.88, title_text, transform=ax.transAxes, ha='center', 
            fontweight='bold', fontsize=10,
            bbox=dict(facecolor='white', alpha=0.7, edgecolor='none', pad=1), zorder=5)
    
    if i >= 8:
        ax.set_xlabel('Epoch', labelpad=1)
    if i % 4 == 0:
        ax.set_ylabel('Log-Likelihood', labelpad=1)
        
    ax.grid(True, linestyle=':', alpha=0.4, zorder=1)
    
    converged_data = lcm_ll.iloc[40:] 
    y_min_focus = min(base_ll_val, converged_data.min())
    y_max_focus = max(base_ll_val, converged_data.max())
    
    y_range = y_max_focus - y_min_focus
    if y_range == 0: y_range = abs(y_max_focus) * 0.05
    
    ax.set_ylim(y_min_focus - y_range * 0.30, y_max_focus + y_range * 0.65)
    
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, p: format(int(x), ',')))
    ax.tick_params(axis='both', which='major', pad=1)
    
    if i == 0:
        leg = ax.legend(loc='lower right', frameon=True, edgecolor='black', framealpha=0.9)
        leg.set_zorder(6)

plt.subplots_adjust(left=0.06, right=0.98, top=0.97, bottom=0.08, wspace=0.18, hspace=0.08)

# Save to PDF
pdf_path = "vit_log_likelihood.pdf"
plt.savefig(pdf_path, dpi=300, bbox_inches='tight', format='pdf')
print(f"Plots saved successfully as: {pdf_path}")

plt.show()