import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# ============================================================
# 1. Configuration & Data Loading
# ============================================================
file_path = 'log_likelihood_values_vit_4_classes.txt'

try:
    df = pd.read_csv(file_path, sep=r'\s+')
except FileNotFoundError:
    print(f"Error: File '{file_path}' not found. Make sure it was generated by the training script.")
    exit()

plt.rcParams.update({
    "text.usetex": False,
    "font.family": "serif",
    "font.size": 14,
    "axes.labelsize": 14,
    "axes.titlesize": 14,
    "xtick.labelsize": 14,
    "ytick.labelsize": 14,
    "legend.fontsize": 14,
    "figure.titlesize": 16
})

layers = [f'block{i}' for i in range(12)]
DIM = 768

# ============================================================
# 2. Plotting (3x4 Grid for 12 Blocks)
# ============================================================
print("\n--- Generating Log-Likelihood Plots for 12 ViT Blocks ---")
fig, axes = plt.subplots(3, 4, figsize=(20, 14))
axes = axes.flatten()

for i, l in enumerate(layers):
    ax = axes[i]
    epochs = df['Epoch']
    
    base_ll_val = df[f'{l}_Baseline'].mean()
    lcm_ll = df[f'{l}_LCM']
    
    ax.axhline(base_ll_val, linestyle='--', linewidth=2.5, color='#7f8c8d', label='Diagonal Covariance')
    
    ax.plot(epochs, lcm_ll, linestyle='-', linewidth=2.5, color='#e67e22', label='Full Covariance')
    
    ax.set_title(f'ViT-B/16 - Block {i} ($D = {DIM:,}$)', fontsize=14, fontweight='bold')
    
    if i >= 8:
        ax.set_xlabel('Epoch', fontsize=14)
    if i % 4 == 0:
        ax.set_ylabel('Total Log-Likelihood', fontsize=14)
        
    ax.grid(True, linestyle=':', alpha=0.6)
    
    y_min_lcm = lcm_ll.iloc[5:].min()
    y_min = min(base_ll_val, y_min_lcm)
    y_max = max(base_ll_val, lcm_ll.max())
    
    y_range = y_max - y_min
    y_margin = y_range * 0.10
    
    if y_range == 0:
        y_margin = abs(y_min) * 0.1
        
    ax.set_ylim(y_min - y_margin, y_max + y_margin)
    
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, p: format(int(x), ',')))
    ax.tick_params(axis='both', which='major', labelsize=14)
    
    if i == 0:
        ax.legend(fontsize=14, loc='lower right')

plt.tight_layout()

# Save to PDF
pdf_path = "vit_12_blocks_log_likelihood.pdf"
plt.savefig(pdf_path, dpi=300, bbox_inches='tight', format='pdf')
print(f"Plots saved successfully as: {pdf_path}")

plt.show()